export const UI_SCENES = {
  NULL: null,
  INTRO: 'INTRO',

  IS_BUYING: 'IS_BUYING',
  IS_SELLING: 'IS_SELLING',
  IS_LEAVING: 'IS_LEAVING',

  IS_BANKING: 'IS_BANKING',
  IS_BORROWING: 'IS_BORROWING',
  IS_STORING: 'IS_STORING',
  IS_BEING_INSPECTED: 'IS_BEING_INSPECTED',

  IS_TRAVELLING: 'IS_TRAVELLING'
};

export const EVENT_TYPES = {
  STORM: 'STORM',
  RAID: 'RAID'
};
